services:

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile

    container_name: infrapilot-frontend

    expose:
      - "80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - infrapilot-network

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile

    container_name: infrapilot-backend

    expose:
      - "5000"

    env_file:
      - .env

    volumes:
      - ../app/database:/app/database

    restart: unless-stopped

    networks:
      - infrapilot-network

  nginx:
    build:
      context: ../nginx

    container_name: infrapilot-nginx

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend

    restart: unless-stopped

    networks:
      - infrapilot-network

  jenkins:
    image: jenkins/jenkins:lts-jdk21

    container_name: infrapilot-jenkins

    restart: unless-stopped

    privileged: true

    user: root

    ports:
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - infrapilot-network

networks:

  infrapilot-network:
    driver: bridge

volumes:

  jenkins_home:

