pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t infrapilot-frontend:latest -f docker/frontend.Dockerfile .'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t infrapilot-backend:latest -f docker/backend.Dockerfile .'
            }
        }

        stage('Build Nginx Image') {
            steps {
                sh 'docker build -t infrapilot-nginx:latest nginx'
            }
        }

        stage('Verify Images') {
            steps {
                sh 'docker images'
            }
        }

        stage('Deploy Containers') {
            steps {
                dir('docker') {
                    sh 'docker compose up -d --build'
                }
            }

            stage('Health Check') {
                steps {
                    sh 'sleep 10'
                    sh 'curl http://host.docker.internal/health'
                }
            }
            
        }
    }

    post {

    success {
        echo '🚀 InfraPilot deployed successfully!'
    }

    failure {
        echo '❌ Deployment failed.'
    }

    always {
        sh 'docker ps'
    }
}